# Generated by Django 6.0.2 on 2026-02-06 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='メーカー名')),
                ('street_address', models.CharField(max_length=255, verbose_name='住所')),
                ('representative_name', models.CharField(max_length=255, verbose_name='代表者名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(upload_to='products/', verbose_name='商品画像')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('stocks', models.PositiveIntegerField(verbose_name='在庫数')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.company', verbose_name='メーカー')),
            ],
        ),
    ]
