# Generated by Django 6.0.2 on 2026-02-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_path',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品画像'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.PositiveIntegerField(default=0, verbose_name='在庫数'),
        ),
    ]
